#!/usr/bin/env python
"""
ADAS Supervision Log Visualizer
===============================

Parses a `.jsonl` blackbox log generated by the `adas_supervision_project` 
and creates a multi-panel dashboard visualizing the simulation over time.

Usage:
    python visualize_log.py path/to/log_blackbox.jsonl
"""

import argparse
import json
import os
import sys

try:
    import matplotlib.pyplot as plt
    import pandas as pd
except ImportError:
    print("Error: This script requires matplotlib and pandas.")
    print("Please install them via: pip install matplotlib pandas")
    sys.exit(1)


def parse_args():
    parser = argparse.ArgumentParser(description="Visualize ADAS Blackbox Logs")
    parser.add_argument("log_path", type=str, help="Path to the .jsonl blackbox file")
    parser.add_argument("--save", action="store_true", help="Save the plot to a PNG instead of displaying it")
    return parser.parse_args()


def load_data(filepath: str):
    """Parse the JSONL file and extract the tick data."""
    if not os.path.exists(filepath):
        print(f"Error: File not found: {filepath}")
        sys.exit(1)

    print(f"Reading log: {filepath}")
    ticks = []
    header = None

    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            try:
                record = json.loads(line)
                if record.get("record_type") == "header":
                    header = record
                elif record.get("record_type") == "tick":
                    # Flatten nested dictionaries for easier pandas conversion
                    if "position" in record:
                        record["pos_x"] = record["position"].get("x", 0)
                        record["pos_y"] = record["position"].get("y", 0)
                        del record["position"]
                    ticks.append(record)
            except json.JSONDecodeError:
                print("Warning: Skipping malformed line.")

    if not ticks:
        print("Error: No tick data found in the log.")
        sys.exit(1)

    df = pd.DataFrame(ticks)
    
    # Ensure time is sorted properly
    if "elapsed_s" in df.columns:
        df = df.sort_values(by="elapsed_s")
    
    return header, df


def plot_dashboard(header, df, save_path=None):
    """Generate the multi-panel matplotlib dashboard."""
    
    print("Generating dashboard...")
    # Set up the figure
    fig, axes = plt.subplots(3, 1, figsize=(12, 12), sharex=True)
    
    sim_id = header.get("simulation_id", "Unknown") if header else "Unknown"
    scenario = header.get("scenario", "Unknown") if header else "Unknown"
    
    fig.suptitle(f"ADAS Supervision Run Analysis\nSimulation ID: {sim_id} | Scenario: {scenario}", fontsize=16)

    time_col = "elapsed_s"
    time = df[time_col]

    # --- Panel 1: Risk & Takeover Stage --- #
    ax1 = axes[0]
    ax1.plot(time, df["risk"], label="Total Risk (Merged)", color="red", linewidth=2)
    
    # Stage Background highlighting
    # Stage 0: Normal -> White
    # Stage 1: Warning -> Light Yellow
    # Stage 2: Speed Reduction -> Light Orange
    # Stage 3: Takeover Request -> Orange
    # Stage 4: Emergency Brake -> Light Coral
    
    ax1.fill_between(time, 0, 1, where=(df["takeover_stage"] == 1), color='yellow', alpha=0.2, label="Stage 1: Warning")
    ax1.fill_between(time, 0, 1, where=(df["takeover_stage"] == 2), color='orange', alpha=0.2, label="Stage 2: Speed Reduction")
    ax1.fill_between(time, 0, 1, where=(df["takeover_stage"] == 3), color='darkorange', alpha=0.3, label="Stage 3: Takeover Request")
    ax1.fill_between(time, 0, 1, where=(df["takeover_stage"] == 4), color='red', alpha=0.2, label="Stage 4: Emergency Brake")

    # Plot Fused Components if they exist
    if "confidence_term" in df.columns and "ttc_term" in df.columns:
        ax1.plot(time, df["confidence_term"], label="Confidence Risk", linestyle=":", color="purple", alpha=0.7)
        ax1.plot(time, df["ttc_term"], label="TTC Risk", linestyle="--", color="blue", alpha=0.7)

    ax1.set_ylabel("Risk Score [0-1]")
    ax1.set_ylim(0, 1.05)
    ax1.legend(loc="upper left", bbox_to_anchor=(1.02, 1), borderaxespad=0.)
    ax1.grid(True, linestyle="--", alpha=0.6)
    ax1.set_title("Risk Assessment & Takeover Escalation")

    # --- Panel 2: Vehicle Telemetry --- #
    ax2 = axes[1]
    ax2.plot(time, df["speed"], label="Speed (m/s)", color="blue", linewidth=2)
    ax2.set_ylabel("Speed (m/s)", color="blue")
    ax2.tick_params(axis='y', labelcolor="blue")
    
    # Create secondary axis for control inputs
    ax2_twin = ax2.twinx()
    ax2_twin.plot(time, df["throttle"], label="Throttle", color="green", alpha=0.8)
    ax2_twin.plot(time, df["brake"], label="Brake", color="red", alpha=0.8)
    ax2_twin.set_ylabel("Control Imput [0-1]", color="black")
    ax2_twin.set_ylim(-0.05, 1.05)
    
    # Combine legends for Panel 2
    lines_1, labels_1 = ax2.get_legend_handles_labels()
    lines_2, labels_2 = ax2_twin.get_legend_handles_labels()
    ax2.legend(lines_1 + lines_2, labels_1 + labels_2, loc="upper left", bbox_to_anchor=(1.1, 1), borderaxespad=0.)
    ax2.grid(True, linestyle="--", alpha=0.6)
    ax2.set_title("Vehicle Dynamics (Speed vs Controls)")

    # --- Panel 3: Perception & Environment --- #
    ax3 = axes[2]
    
    if "min_ttc" in df.columns:
        # Cap TTC for visualisation purposes to avoid massive spikes destroying the plot scale
        ttc_plot = df["min_ttc"].fillna(10.0).clip(upper=10.0) 
        ax3.plot(time, ttc_plot, label="Min TTC (capped 10s)", color="teal", linewidth=2)
    
    ax3.set_ylabel("Time to Collision (s)", color="teal")
    ax3.tick_params(axis='y', labelcolor="teal")
    ax3.set_xlabel("Elapsed Time (s)")
    ax3.set_ylim(0, 10.5)

    ax3_twin = ax3.twinx()
    ax3_twin.plot(time, df["detections"], label="Object Detections", color="brown", linestyle="--")
    ax3_twin.set_ylabel("Number of Detected Objects", color="brown")
    ax3_twin.tick_params(axis='y', labelcolor="brown")
    
    lines_3, labels_3 = ax3.get_legend_handles_labels()
    lines_4, labels_4 = ax3_twin.get_legend_handles_labels()
    ax3.legend(lines_3 + lines_4, labels_3 + labels_4, loc="upper left", bbox_to_anchor=(1.1, 1), borderaxespad=0.)
    ax3.grid(True, linestyle="--", alpha=0.6)
    ax3.set_title("Perception Data")

    plt.tight_layout()
    fig.subplots_adjust(right=0.82) # Make room for external legends

    if save_path:
        print(f"Saving dashboard to: {save_path}")
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
    else:
        plt.show()

def main():
    args = parse_args()
    header, df = load_data(args.log_path)
    
    save_path = None
    if args.save:
        base = os.path.splitext(args.log_path)[0]
        save_path = f"{base}_dashboard.png"
        
    plot_dashboard(header, df, save_path)
    print("Dashboard generation complete.")

if __name__ == "__main__":
    main()
